version: '2'
services:
  server:
    build: .
    command: nodemon server/
    links:
      - mongo
    ports:
      - 3131:3030
    volumes:
      - /src/node_modules
      - .:/src
      - ./.data/images:/images
  mongo:
    image: mongo
    volumes:
      - ./.data/database:/data/db
    ports:
      - 27018:27017
