version: '2'
services:
  server:
    build: .
    command: nodemon server/
    links:
      - mongo
    ports:
      - 3131:3131
    volumes:
      - /src/node_modules
      - .:/src
      - ./.data/images:/images
    environment:        
      NODE_CONFIG: |-
          {
            "mongoConnectionString": "mongodb://mongo/agenda",
            "imagesPath": "/images"
          }
  mongo:
    image: mongo
    volumes:
      - ./.data/database:/data/db
    ports:
      - 27018:27017
